import React from "react";
export const MENUITEMS = [
  // {
  // 	menutitle: '',
  // },
  // {
  // 	icon: (<i className="bi bi-house side_menu_img"></i>),
  // 	type: 'sub',
  // 	Name: '',
  // 	active: false,
  // 	selected: false,
  // 	title: 'CRM',
  // 	badge: '',
  // 	badgetxt: '',
  // 	class: '',
  // 	children: [
  // 		{ id: 3, path: `${import.meta.env.BASE_URL}crm/crmdashboard`, type: "link", active: false, selected: false, title: "Dashboard" },
  // 	]
  // },

  {
    menutitle: "",
  },
  // {
  //   icon: <i className="bi bi-bar-chart side_menu_img"></i>,
  //   type: "sub",
  //   Name: "",
  //   active: false,
  //   selected: false,
  //   badge: "",
  //   badgetxt: "",
  //   class: " ",
  //   title: "Charts",
  //   children: [
  //     {
  //       title: "Apex Charts",
  //       type: "sub",
  //       selected: false,
  //       active: false,
  //       children: [
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/linecharts`,
  //           title: "Line Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/areacharts`,
  //           title: "Area Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/columncharts`,
  //           title: "Column Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/barcharts`,
  //           title: "Bar Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/mixedcharts`,
  //           title: "Mixed Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/rangeareacharts`,
  //           title: "Range Area Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/timelinecharts`,
  //           title: "Timeline Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/candlestickcharts`,
  //           title: "CandleStick Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/boxplotcharts`,
  //           title: "Boxplot Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/bubblecharts`,
  //           title: "Bubble Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/scattercharts`,
  //           title: "Scatter Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/heatmapcharts`,
  //           title: "Heatmap Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/treemapcharts`,
  //           title: "Treemap Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/piecharts`,
  //           title: "Pie Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/radialbarcharts`,
  //           title: "Radialbar Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/radarcharts`,
  //           title: "Radar Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //         {
  //           path: `${import.meta.env.BASE_URL}apexcharts/polarareacharts`,
  //           title: "Polararea Charts",
  //           type: "link",
  //           active: false,
  //           selected: false,
  //         },
  //       ],
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}charts/chartjscharts`,
  //       title: "Chartjs Charts",
  //       type: "link",
  //       active: false,
  //       selected: false,
  //     },
  //     {
  //       path: `${import.meta.env.BASE_URL}charts/echartscharts`,
  //       title: "Echart Charts",
  //       type: "link",
  //       active: false,
  //       selected: false,
  //     },
  //   ],
  // },

  {
    menutitle: "",
  },

  {
    icon: <i className="bi bi-cart2 side_menu_img"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    badge: "",
    badgetxt: "",
    class: "",
    title: "KPI Manager",
    children: [
      {
        id: 24,
        path: `${import.meta.env.BASE_URL}ecommerce/dashboard`,
        type: "link",
        active: false,
        selected: false,
        title: "Reports",
      },
    ],
  },

  {
    icon: <i className="bi bi-list side_menu_img"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    badge: "",
    badgetxt: "",
    class: "",
    title: "Listing Segments",
    children: [
      {
        id: 25,
        path: `${import.meta.env.BASE_URL}listing-segments/active`,
        type: "link",
        active: false,
        selected: false,
        title: "Active",
      },
      {
        id: 26,
        path: `${import.meta.env.BASE_URL}listing-segments/ended`,
        type: "link",
        active: false,
        selected: false,
        title: "Ended",
      },
    ],
  },

  {
    icon: <i className="fe fe-download me-1 side_menu_img"></i>,
    path: `${import.meta.env.BASE_URL}uploadmanager`,
    type: "link",
    active: false,
    selected: false,
    title: "Upload Manager",
  },

  // {
  // 	menutitle: "",
  // },
  // {
  // 	icon: (<i className="bx bx-layer side_menu_img"></i>),
  // 	type: "sub",
  // 	Name: '',
  // 	active: false,
  // 	selected: false,
  // 	badge: '',
  // 	badgetxt: '',
  // 	class: ' ',
  // 	title: "Nested Menu",
  // 	children: [
  // 		{
  // 			path: '',
  // 			title: "Nested-1",
  // 			type: "empty",
  // 			active: false,
  // 			selected: false,
  // 		},
  // 		{
  // 			title: "Nested-2",
  // 			type: "sub",
  // 			selected: false,
  // 			active: false,
  // 			children: [
  // 				{
  // 					path: '',
  // 					title: "Nested-2.1",
  // 					type: "empty",
  // 					active: false,
  // 					selected: false,
  // 				},
  // 				{
  // 					path: '',
  // 					title: "Nested-2.2",
  // 					type: "empty",
  // 					active: false,
  // 					selected: false,
  // 				},

  // 			],
  // 		},
  // 	],
  // }
];
